# Generated by Django 5.1.1 on 2024-10-03 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('TODO', 'To-Do'), ('DAILY', 'Daily'), ('HABIT', 'Habit')], default='HABIT', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
